# Generated by Django 4.2.5 on 2023-10-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuum_Cleaner_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Twin_Washing_Machine_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerator_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Dishwasher_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Auto_Washing_Machine_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brands')),
            ],
        ),
    ]
