# Generated by Django 4.2.5 on 2023-12-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_washing_machine_models',
            name='model_brand',
        ),
        migrations.RemoveField(
            model_name='dishwasher_models',
            name='model_brand',
        ),
        migrations.RemoveField(
            model_name='refrigerator_models',
            name='model_brand',
        ),
        migrations.RemoveField(
            model_name='twin_washing_machine_models',
            name='model_brand',
        ),
        migrations.RemoveField(
            model_name='vacuum_cleaner_models',
            name='model_brand',
        ),
        migrations.DeleteModel(
            name='Accessory_models',
        ),
        migrations.DeleteModel(
            name='Auto_Washing_Machine_models',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Dishwasher_models',
        ),
        migrations.DeleteModel(
            name='Refrigerator_models',
        ),
        migrations.DeleteModel(
            name='Twin_Washing_Machine_models',
        ),
        migrations.DeleteModel(
            name='Vacuum_Cleaner_models',
        ),
    ]
