# Generated by Django 4.2.5 on 2023-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_washing_machine_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_washing_machine_part',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
