# Generated by Django 4.2.5 on 2023-12-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_model_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
