# Generated by Django 4.2.5 on 2023-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_part_category_part_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
