# Generated by Django 4.2.5 on 2023-12-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_category_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
