# Generated by Django 4.2.5 on 2023-12-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_model_model_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='model',
            name='model_brand',
        ),
        migrations.RemoveField(
            model_name='model',
            name='model_category',
        ),
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
        migrations.RemoveField(
            model_name='part',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='part',
            name='used_models',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
