# Generated by Django 4.2.5 on 2023-12-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
