# Generated by Django 4.2.5 on 2023-12-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sub_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
