# Generated by Django 4.2.5 on 2023-12-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_model_name_alter_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='category_icons'),
        ),
    ]
