# Generated by Django 4.2.5 on 2023-12-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_model_icon_sub_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='category_icons'),
        ),
    ]
