# Generated by Django 4.2.5 on 2023-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_sub_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='images/default.png', height_field='image_height', upload_to='category_icons', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='category_icons'),
        ),
    ]
