# Generated by Django 4.2.5 on 2023-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_category_icon_alter_sub_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='category_icons'),
        ),
    ]
