# Generated by Django 4.2.5 on 2023-12-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='popular',
            field=models.BooleanField(default=True),
        ),
    ]
