# Generated by Django 4.2.5 on 2023-12-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_part_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='discoundet_price',
            new_name='discounted_price',
        ),
    ]
