# Generated by Django 4.2.5 on 2023-12-19 08:02

from django.db import migrations, models
import django.db.models.deletion
import main.misc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_discoundet_price_part_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', upload_to=main.misc.get_images_upload_path)),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.part')),
            ],
        ),
    ]
