# Generated by Django 4.2.5 on 2023-12-19 10:02

from django.db import migrations, models
import main.misc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_part_image_partimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image',
        ),
        migrations.AddField(
            model_name='part',
            name='image_tumbnail',
            field=models.ImageField(blank=True, default='images/default.png', upload_to=main.misc.get_tumbnail_upload_path),
        ),
    ]
