# Generated by Django 4.2.5 on 2023-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_part_image_part_image_tumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='used_models',
        ),
        migrations.AddField(
            model_name='part',
            name='used_models',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
